### ISSUE TITLE
Respect "\" in long import statements

### ISSUE THREAD

**Issue by eugenet8k** [helixbass/prettier-plugin-coffeescript#163]
Hi, thanks for your great work with this plugin! We found one problem that we couldn't overcome via config.

If we have a long import statement, we usually use "\" to break to a new line:
```
import MyVeryVeryVeryLongName \
  from '../views/namespace/very/long/sub/folder/module'
```

Prettier forces it to become a one-liner:
```
import MyVeryVeryVeryLongName from '../views/namespace/very/long/sub/folder/module'
```

Which immediately triggers an error:
```
Line exceeds maximum allowed length (max_line_length)
```

**Comment by helixbass** [comment]
Hi,

Ok so far I've avoided any options for using backslashes for line continuation, but it could be considered whether to expose an option for formatting long `import`'s with a backslash like this

But separate from whether to support your existing backslash formatting, I think the issue here is that `max_line_length` should be disabled for projects that use Prettier - basically Prettier does its best to keep lines under its configured `printWidth` (default 80), but can't guarantee it in all situations

Eg your example code also "overflows" with Prettier for JS ([playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgFkBPANThzIqsoBloBzAOQEN058AzHCdfAcgB0ggPQA3VHADuAZxFQ2cGZhZg446iIA2jETICuAIxGcIWgCYUR6COf1a4-ADpQQAGhARMMVNBnJQFhweKQAFIIR-FBYxCFRzdxBDHFUAazgYAGUVMFQoBmQYHH04DwALGHQtAHUy1HhlVThMyPrUCRhiZHAZfw88mQoYUJSGdBZkThYtQY8AKxkADwAhFLB0rMVaPLhJ6dmQBcXMvIYHAEV9CHg9mdKQFRxBnG7DFkM4LUTMHDyYaviMDKyAAHAAGDw-CCDaopTDdH5KChiXYeACOV3gIy8URALBkAFooHA4JYEh4cHAMahKSMWGMJkgpncPIN0KhCsV7jJThdMbsmft7jB3gDzEDkAAmDxFFioLSnADCvHG3Sg0FRIH0gwAKu8osyDmISgBJKCWWCZMC-bwAQXNmU6DlugwAvq6gA))

So I'm not sure what exactly enforces `max_line_length` in your project setup, but I'd recommend disabling it for filetypes that Prettier is formatting (this is very similar to how `eslint-config-prettier` [disables the `max-len` ESLint rule](https://github.com/prettier/eslint-config-prettier/blob/master/index.js#L14))

**Comment by eugenet8k** [comment]
@helixbass good point, actually I also have no idea what plugin reports this error. I thought it is coming from ESLint but it is not since the command line command does not yield this error, I can see it only in VSCode:

<img width="651" alt="vscode-error" src="https://user-images.githubusercontent.com/4804824/73025312-389ef200-3de4-11ea-969c-bc2eabb6c4a1.png">

Moreover, indeed recent edition of Prettier ignores max length overflows for lines that just have long strings (imports with long file name paths fall into this set). As you demonstrated in the playground link.

It must be some weird combination of JS and CS ESLint plugins that we have in our project... But VSCode does not show this error for regular JS files, only for CoffeeScript ones at this point.

Would it be possible that this fork of Prettier is based on some older upstream Prettier that still treats lines with long strings as overflow?

**Comment by eugenet8k** [comment]
OK, the culprit has been found. While I migrated to CoffeeScript ESLint checks I forgot to kill the older `coffeelint` and the related VSCode plugin https://marketplace.visualstudio.com/items?itemName=freewil.vscode-coffeelint2. Sorry for false alarm!

**Comment by GeoffreyBooth** [comment]
@eugenet8k Is your project public or could it be? It would be useful to have it, or at least its building/linting/reformatting configuration, available as an example for others.

**Comment by helixbass** [comment]
Ya I think it'd be worth adding a section to the `eslint-plugin-coffee` (@GeoffreyBooth if you've also been following https://github.com/helixbass/eslint-plugin-coffee/issues/33) README describing a "mixed JS + Coffeescript setup", I just wanted to wrap my head more around eg how `overrides` works first
