### ISSUE TITLE
element.classList removed for some reason

### ISSUE THREAD

**Issue by localhostdotdev** [helixbass/prettier-plugin-coffeescript#80]
I know this is very early, but letting you know it's removing element.classList, e.g. here is a code sample:

```coffee
# cat app/assets/javascripts/confirm.coffee
WAITING_CLASS = "waiting-for-confirmation"
TIMEOUT = 2000

Rails.confirm = (message, element) ->
  if element.classList.contains(WAITING_CLASS)
    true
  else
    element.dataset.beforeConfirm = element.textContent
    element.textContent = element.dataset.confirm
    element.classList.add(WAITING_CLASS)

    timeout TIMEOUT, ->
      element.classList.remove(WAITING_CLASS)
      element.textContent = element.dataset.beforeConfirm

    false

# prettier app/assets/javascripts/confirm.coffee
WAITING_CLASS = 'waiting-for-confirmation'
TIMEOUT = 2000

Rails.confirm = (message, element) ->
  if .contains WAITING_CLASS
    true
  else
    element.dataset.beforeConfirm = element.textContent
    element.textContent = element.dataset.confirm
    .add WAITING_CLASS

    timeout TIMEOUT, ->
      .remove WAITING_CLASS
      element.textContent = element.dataset.beforeConfirm

    false
```

Using 92428e9edbe3f27f8fe4235bd7b4f621d2e5fed5, prettier 395e5d5c coffeescript bb034dc0

**Comment by helixbass** [comment]
Ok looks like it was picking up the wrong version of Prettier from dependencies. The dependencies are fragile at this point but this should work:

```
$ yarn add --dev prettier-plugin-coffeescript@^0.0.8
$ rm yarn.lock && yarn install
```

At that point it should pick up the correct version of Prettier. So if you run
```
$ yarn prettier app/assets/javascripts/confirm.coffee
```
it should be formatted correctly, let me know if you still run into problems

**Comment by helixbass** [comment]
@localhostdotdev I think the recommended approach to ensure the correct dependencies are used should actually be to explicitly install them

I updated the [README](https://github.com/helixbass/prettier-plugin-coffeescript) to include installation instructions (and other documentation), so please take a look there

I tested this approach with a sample project where I first installed Prettier and the Prettier Ruby plugin and then installed the Coffeescript plugin and it was correctly formatting both `.rb` and `.coffee` files

**Comment by localhostdotdev** [comment]
is there a way to use it without having to install a specific commit of a forked version of prettier?

**Comment by helixbass** [comment]
Not currently - in order to format Coffeescript nicely, new Prettier primitives were required (if you're curious, have a look at https://github.com/prettier/prettier/pull/4462)

Once I have the plugin a little more robust it will be a priority to get that merged into mainstream Prettier. So it should only be temporary to need a forked Prettier dependency

The forked version of Prettier should be completely backwards-compatible and is based on a relatively new version of Prettier (around 1.16 - if you needed an even newer version of Prettier, I could rebase onto latest `master`)

As far as needing to specify a specific commit, I'm not an expert in `npm`/`yarn` dependencies but I've found that if I specify a branch-name Github dependency eg `github:helixbass/prettier#visible-group` they get very confused and don't update to latest commits reliably (I'm guessing this has to do with version numbers of the package in `package.json`?)

By specifying a specific commit eg `github:helixbass/prettier#72ae1f97`, `npm`/`yarn` are at least more reliable. But I've still seen them both get confused, which is why in the README I recommend `rm yarn.lock` before installing the dependencies

Not sure if there would be any other good options for specifying/distributing the forked dependency - I could temporarily create a separate NPM package eg `prettier-with-visible-groups` but that would probably mess up integrations that expect to eg `require('prettier')` - basically I don't think it should live side-by-side with other Prettier version, it should be *the* Prettier dependency in the project
